version: '3.8'

services:
  # Database service based on PostgreSQL
  db:
    image: postgres:15
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service based on Spring Boot
  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  # Frontend service based on Next.js
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
