services:
  # Database service based on MySQL
  db:
    image: mysql:8
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h localhost -u root -proot || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service based on Spring Boot
  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  # Frontend service based on Next.js
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
