name: Deploy to EC2 with Code Sync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. EC2로 프로젝트 전송
      - name: Upload Project to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TEST_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: './' # 로컬 Github Actions 워크스페이스 전체
          target: '/home/ubuntu/zzrrt' # EC2에 저장될 경로

      # 3. Docker Compose 명령 실행
      - name: Deploy to EC2 with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}/zzrrt
            docker-compose down
            docker-compose up -d frontend
