name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy Backend
        run: |
          sshpass -p "${{ secrets.EC2_PASSWORD }}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -r ./ ubuntu@${{ secrets.BACKEND_EC2_IP }}:/home/ubuntu/project
          sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password ubuntu@${{ secrets.BACKEND_EC2_IP }} << 'EOF'
          cd /home/ubuntu/project
          docker compose down
          docker compose up -d --build backend
          EOF

      - name: Deploy Frontend
        run: |
          sshpass -p "${{ secrets.EC2_PASSWORD }}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -r ./ ubuntu@${{ secrets.FRONTEND_EC2_IP }}:/home/ubuntu/project
          sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password ubuntu@${{ secrets.FRONTEND_EC2_IP }} << 'EOF'
          cd /home/ubuntu/project
          docker compose down
          docker compose up -d --build frontend
          EOF
